// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjhux9UxAEHzzj3iysb76P1kQBvU4I2E',
    appId: '1:942045168384:web:a96e58bdcc99a0075229e5',
    messagingSenderId: '942045168384',
    projectId: 'iti-project-17989',
    authDomain: 'iti-project-17989.firebaseapp.com',
    storageBucket: 'iti-project-17989.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6u9u65-EUDpxajTZkwshKTwsb_vbSd_4',
    appId: '1:942045168384:android:b64e7f05f1899bf75229e5',
    messagingSenderId: '942045168384',
    projectId: 'iti-project-17989',
    storageBucket: 'iti-project-17989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXhPAdrn2odv9MoMQbrfJfAyq2dxZ9S0',
    appId: '1:942045168384:ios:118996011e6eaf2b5229e5',
    messagingSenderId: '942045168384',
    projectId: 'iti-project-17989',
    storageBucket: 'iti-project-17989.appspot.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBXhPAdrn2odv9MoMQbrfJfAyq2dxZ9S0',
    appId: '1:942045168384:ios:118996011e6eaf2b5229e5',
    messagingSenderId: '942045168384',
    projectId: 'iti-project-17989',
    storageBucket: 'iti-project-17989.appspot.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIjhux9UxAEHzzj3iysb76P1kQBvU4I2E',
    appId: '1:942045168384:web:f188fec6a446d6675229e5',
    messagingSenderId: '942045168384',
    projectId: 'iti-project-17989',
    authDomain: 'iti-project-17989.firebaseapp.com',
    storageBucket: 'iti-project-17989.appspot.com',
  );
}
